# Generated by Django 3.2.8 on 2021-10-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_cartitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='url',
            field=models.FileField(upload_to='item_images'),
        ),
    ]
